#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ListViewAnimationTest.Resource", IsApplication=true)]

namespace ListViewAnimationTest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int edit_text_style = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int filefind = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_search = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int layout_bg = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ShiPinImageButtonClickStyle = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000b
			public const int ContentText = 2131099659;
			
			// aapt resource value: 0x7f060003
			public const int ListViewContainer = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int ProgressbarTextViewLayout = 2131099656;
			
			// aapt resource value: 0x7f060001
			public const int activity_expandablelistitem_card_content = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int activity_expandablelistitem_card_title = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int activity_mylist_listview = 2131099652;
			
			// aapt resource value: 0x7f06000c
			public const int chaGangBtn = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int enterBtn = 2131099661;
			
			// aapt resource value: 0x7f060006
			public const int etSearch = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int item_separator = 2131099650;
			
			// aapt resource value: 0x7f06000e
			public const int list_row_draganddrop_textview = 2131099662;
			
			// aapt resource value: 0x7f06000a
			public const int loadMoreTextView = 2131099658;
			
			// aapt resource value: 0x7f06000f
			public const int myButton = 2131099663;
			
			// aapt resource value: 0x7f060009
			public const int progressbarLoadMore = 2131099657;
			
			// aapt resource value: 0x7f060010
			public const int search = 2131099664;
			
			// aapt resource value: 0x7f060007
			public const int searchBtn = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int searchLayout = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_expandablelistitem_card = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_mylist = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int expand_content_layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int list_row = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int actionbar = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int expandorcollapsecard = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
